<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function(Category $category){
            $category->slug = $category->slug ?? str($category->title)->slug();
        });
    }

    public function products()
    {
        return $this->belongsToMany(Category::class);
    }
}
